inputs:
  module:
    description: “The module to run”
    required: true

runs:
  using: "composite"
  steps:
    - id: install
      name: Install Python, pipenv and Pipfile packages
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

      name: Install pipenv
      run: |
        curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        pipenv install

    - id: make
      name: Run make command
      run: make -f ./${{ inputs.module }}/Makefile
      shell: bash

    - id: commit
      name: Commit results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "actions@github.com"
        git config pull.rebase false
        git status
        git pull origin $GITHUB_REF
        git add ./
        git commit -m "${{ inputs.module }} scrape" && git push || true
      shell: bash
