name: Bed surges
on:
  schedule:
    - cron: '10 */4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: ./.github/actions/scrape
        with:
          module: bed-surges
