name: Bed surges
on:
  schedule:
    - cron: '10 */4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.8

      - name: Run scraper
        uses: ./.github/actions/scrape
        with:
          module: bed-surges
