name: LAUSD-scrape
on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  scrapeLAUSD:
    name: Scrape
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
         python-version: 3.8
          
      - id: install-chromedriver
        name: Install chromedriver
        uses: nanasess/setup-chromedriver@master

      - name: Scrape
        shell: bash
        run: |
          pipenv run python lausd-cases/scrape.py

      - name: Add and commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git pull origin main
          git add lausd-cases/
          git commit -m "Downloading LAUSD case counts on $(TZ=America/Los_Angeles date +"%r on %F")" 
          
      - name: Push changes
        uses: ad-m/github-push-action@master
