name: Places
on:
  schedule:
    - cron: '10 */12 * * *'
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: python-install
        name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.8

      - id: chromium-install
        name: Playwright install of Chromium
        run: pipenv run playwright install chromium

      - id: make
        name: Run make command
        run: make -f ./places/Makefile
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: commit
        name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git status
          git pull origin $GITHUB_REF
          git add ./
          git commit -m "places scrape" && git push || true
        shell: bash
