name: Skilled-nursing totals
on:
  schedule:
    - cron: '10 */4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install-chromedriver
        name: Install chromedriver
        uses: nanasess/setup-chromedriver@master

      - id: run
        name: Run
        uses: ./.github/actions/scrape
        with:
          module: skilled-nursing-totals
