name: Notebook tests
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: | 
          sudo apt update
          sudo apt install -y poppler-utils

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v1
        with:
          python-version: 3.8

      - name: Lint notebooks
        run: make lint_notebooks

