name: Vaccine shipped and delivered
on:
  schedule:
    - cron: '40 */4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v1
        with:
          python-version: 3.8
      
      - name: Run
        run: make -f ./vaccine-shipped-delivered/Makefile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        uses: ./.github/actions/commit
        if: always()
        with:
            message: vaccine-shipped-delivered scrape
